from flask import Flask, render_template, jsonify, session
import random

app = Flask(__name__)
app.secret_key = "secret_key"  # Required for session management

# 200 words with hints
WORDS = [
  {"word": "apple", "hint": "A red or green fruit"},
  {"word": "banana", "hint": "A long yellow fruit"},
  {"word": "orange", "hint": "A round citrus fruit"},
  {"word": "grapes", "hint": "Small, round fruit"},
  {"word": "mango", "hint": "A sweet tropical fruit"},
  {"word": "peach", "hint": "A soft, juicy fruit"},
  {"word": "lemon", "hint": "A sour yellow fruit"},
  {"word": "carrot", "hint": "An orange vegetable"},
  {"word": "potato", "hint": "Used to make fries"},
  {"word": "tomato", "hint": "A red vegetable"},
  {"word": "onion", "hint": "Makes people cry"},
  {"word": "butter", "hint": "Spread for bread"},
  {"word": "cheese", "hint": "Made from milk"},
  {"word": "honey", "hint": "Made by bees"},
  {"word": "pepper", "hint": "A common spice"},
  {"word": "basket", "hint": "Used to carry things"},
  {"word": "bottle", "hint": "Holds water or juice"},
  {"word": "mirror", "hint": "Reflects your image"},
  {"word": "window", "hint": "Lets in light"},
  {"word": "rocket", "hint": "Flies to space"},
  {"word": "school", "hint": "A place to learn"},
  {"word": "pencil", "hint": "Used for writing"},
  {"word": "marker", "hint": "Used to draw bold lines"},
  {"word": "eraser", "hint": "Removes pencil marks"},
  {"word": "notebook", "hint": "Used to write notes"},
  {"word": "laptop", "hint": "A portable computer"},
  {"word": "remote", "hint": "Used to control TV"},
  {"word": "wallet", "hint": "Holds money and cards"},
  {"word": "pillow", "hint": "Soft, used for sleeping"},
  {"word": "tissue", "hint": "Used to wipe your nose"},
  {"word": "jacket", "hint": "Worn to keep warm"},
  {"word": "helmet", "hint": "Protects your head"},
  {"word": "blanket", "hint": "Keeps you warm in bed"},
  {"word": "flower", "hint": "A colorful, fragrant plant"},
  {"word": "garden", "hint": "Has flowers and plants"},
  {"word": "bridge", "hint": "Helps cross a river"},
  {"word": "ladder", "hint": "Used to climb up"},
  {"word": "painter", "hint": "Uses colors on a canvas"},
  {"word": "singer", "hint": "Someone who sings"},
  {"word": "dancer", "hint": "Moves to music"},
  {"word": "driver", "hint": "Controls a vehicle"},
  {"word": "doctor", "hint": "Helps sick people"},
  {"word": "farmer", "hint": "Grows crops"},
  {"word": "baker", "hint": "Makes bread and cakes"},
  {"word": "police", "hint": "Helps keep people safe"},
  {"word": "sailor", "hint": "Works on a boat"},
  {"word": "forest", "hint": "Has many trees"},
  {"word": "desert", "hint": "A dry, sandy place"},
  {"word": "island", "hint": "Land surrounded by water"},
  {"word": "beach", "hint": "Sandy place near the ocean"},
  {"word": "ocean", "hint": "A large body of water"},
  {"word": "river", "hint": "Flows with water"},
  {"word": "bridge", "hint": "Crosses over water"},
  {"word": "tunnel", "hint": "A passage under the ground"},
  {"word": "castle", "hint": "A large, old building"},
  {"word": "garden", "hint": "Has flowers and plants"},
  {"word": "candle", "hint": "Gives light when burned"},
  {"word": "shadow", "hint": "Made by blocking light"},
  {"word": "guitar", "hint": "A stringed musical instrument"},
  {"word": "violin", "hint": "A small, stringed instrument"},
  {"word": "piano", "hint": "A keyboard musical instrument"},
  {"word": "trumpet", "hint": "A brass wind instrument"},
  {"word": "camera", "hint": "Takes pictures"},
  {"word": "ticket", "hint": "Needed for entry"},
  {"word": "puzzle", "hint": "A game to solve"},
  {"word": "lantern", "hint": "A portable light source"},
  {"word": "frozen", "hint": "Turned into ice"},
  {"word": "fridge", "hint": "Keeps food cold"},
  {"word": "planet", "hint": "Orbits around a star"},
  {"word": "saturn", "hint": "A planet with rings"},
  {"word": "pluto", "hint": "A dwarf planet"},
  {"word": "meteor", "hint": "A rock from space"},
  {"word": "comet", "hint": "A space rock with a tail"},
  {"word": "robot", "hint": "A machine that works"},
  {"word": "rocket", "hint": "Flies into space"},
  {"word": "spaceship", "hint": "Travels beyond Earth"},
  {"word": "parrot", "hint": "A bird that talks"},
  {"word": "rabbit", "hint": "A small animal with long ears"},
  {"word": "turtle", "hint": "A slow-moving reptile"},
  {"word": "cheetah", "hint": "The fastest land animal"},
  {"word": "panda", "hint": "A black and white bear"},
  {"word": "dolphin", "hint": "A smart sea animal"},
  {"word": "whale", "hint": "The biggest sea animal"},
  {"word": "eagle", "hint": "A bird with sharp eyes"},
  {"word": "butterfly", "hint": "A flying insect with colorful wings"},
  {"word": "spider", "hint": "Has eight legs"},
  {"word": "tiger", "hint": "A big cat with stripes"},
  {"word": "elephant", "hint": "A big animal with a trunk"},
  {"word": "monkey", "hint": "Loves to climb trees"},
  {"word": "zebra", "hint": "A striped black-and-white animal"},
  {"word": "penguin", "hint": "A bird that cannot fly"},
  {"word": "ostrich", "hint": "The largest bird"},
  {"word": "cloud", "hint": "White and fluffy in the sky"},
  {"word": "rainbow", "hint": "Has many colors in the sky"},
  {"word": "sunlight", "hint": "Comes from the sun"},
  {"word": "sunflower", "hint": "A tall yellow flower"},
  {"word": "diamond", "hint": "A precious stone"},
  {"word": "golden", "hint": "A shiny yellow color"},
  {"word": "silver", "hint": "A shiny metal"},
  {"word": "wallet", "hint": "Holds money"},
  {"word": "glasses", "hint": "Helps people see better"},
  {"word": "bicycle", "hint": "A two-wheeled vehicle"},
  {"word": "giraffe", "hint": "A tall animal with a long neck"},
  {"word": "castle", "hint": "A large old building"},
  {"word": "scooter", "hint": "A small, two-wheeled vehicle"},
  {"word": "lantern", "hint": "A portable light source"},
  {"word": "umbrella", "hint": "Used when it rains"},
  {"word": "fireworks", "hint": "Bright lights in the sky"},
  {"word": "backpack", "hint": "Used to carry things on your back"},
  {"word": "apple", "hint": "A common fruit that keeps the doctor away"},
  {"word": "table", "hint": "A piece of furniture with four legs"},
  {"word": "ocean", "hint": "A vast body of salt water"},
  {"word": "piano", "hint": "A musical instrument with black and white keys"},
  {"word": "zebra", "hint": "A striped animal found in Africa"},
  {"word": "chair", "hint": "A seat for one person"},
  {"word": "grape", "hint": "A small fruit used to make wine"},
  {"word": "cloud", "hint": "A visible mass of condensed water vapor"},
  {"word": "river", "hint": "A large natural stream of water"},
  {"word": "flute", "hint": "A musical instrument that is played by blowing air"},
  {"word": "eagle", "hint": "A large bird of prey with sharp vision"},
  {"word": "bread", "hint": "A staple food made from flour and water"},
  {"word": "house", "hint": "A building for people to live in"},
  {"word": "clock", "hint": "A device used to tell time"},
  {"word": "sugar", "hint": "A sweet substance used in food and drinks"},
  {"word": "lemon", "hint": "A sour yellow fruit"},
  {"word": "train", "hint": "A series of connected railroad cars"},
  {"word": "beach", "hint": "A sandy shore by the ocean or lake"},
  {"word": "candy", "hint": "A sweet treat often enjoyed by kids"},
  {"word": "tiger", "hint": "A large cat with orange fur and black stripes"},
  {"word": "plane", "hint": "A flying vehicle with wings"},
  {"word": "grill", "hint": "A cooking device used for barbecuing"},
  {"word": "horse", "hint": "A large animal often used for riding"},
  {"word": "shirt", "hint": "A piece of clothing worn on the upper body"},
  {"word": "melon", "hint": "A large round fruit with a thick rind"},
  {"word": "music", "hint": "An art form using sound and rhythm"},
  {"word": "stone", "hint": "A small piece of rock"},
  {"word": "pencil", "hint": "A tool used for writing or drawing"},
  {"word": "gravel", "hint": "Small loose stones used for paths"},
  {"word": "carrot", "hint": "An orange vegetable often eaten raw"},
  {"word": "forest", "hint": "A large area covered with trees"},
  {"word": "school", "hint": "A place where students learn"},
  {"word": "helmet", "hint": "A protective headgear"},
  {"word": "wallet", "hint": "A small case for carrying money"},
  {"word": "banana", "hint": "A yellow fruit that monkeys love"},
  {"word": "breeze", "hint": "A light wind"},
  {"word": "pocket", "hint": "A small pouch sewn into clothing"},
  {"word": "bottle", "hint": "A container used to hold liquids"},
  {"word": "market", "hint": "A place where goods are bought and sold"},
  {"word": "rocket", "hint": "A vehicle used for space travel"},
  {"word": "garden", "hint": "A place where plants and flowers grow"},
  {"word": "island", "hint": "A land surrounded by water"},
  {"word": "basket", "hint": "A container made of woven material"},
  {"word": "soccer", "hint": "A sport played with a round ball"},
  {"word": "bridge", "hint": "A structure built to cross a river or road"},
  {"word": "window", "hint": "An opening in a wall for light and air"},
  {"word": "purple", "hint": "A color that is a mix of blue and red"},
  {"word": "guitar", "hint": "A musical instrument with strings"},
  {"word": "shadow", "hint": "A dark shape cast by an object blocking light"},
  {"word": "castle", "hint": "A large fortified building"},
  {"word": "camera", "hint": "A device used to take pictures"},
]

def get_random_word():
    word_data = random.choice(WORDS)
    word = word_data["word"]
    hint = word_data["hint"]
    hint_letters = ''.join([letter if random.random() > 0.5 else '_' for letter in word])
    return {"word": word, "hint": hint, "hint_letters": hint_letters}

@app.route('/')
def index():
    session["score"] = 0  # Reset score on page refresh
    return render_template('index.html', score=session["score"])

@app.route('/get_word')
def get_word():
    return jsonify(get_random_word())

@app.route('/update_score', methods=['POST'])
def update_score():
    session["score"] += 10
    return jsonify({"score": session["score"]})

if __name__ == '__main__':
    app.run(debug=True)
